version: '3.4'

services:
  frontend:
    build:
      context: https://github.com/robinferm/jobs-in-sweden-FE.git#main
      dockerfile: ./Dockerfile.prod

  backend:
    build:
      context: https://github.com/robinferm/jobs-in-sweden-BE.git#main
      dockerfile: ./JIS-BE/Dockerfile
  
  mongo:
    image: mongo:4.4.11-rc0-focal # For linux
    volumes:
      - ../mongodb/database:/data/db