version: '3.4'

services:
  frontend:
    container_name: frontend
    restart: always
    depends_on:
      - backend

  backend:
    container_name: backend
    restart: always
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    restart: always
    
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - 80:80